# Generated by Django 4.2.16 on 2026-04-08 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('last_public_activity', models.DateTimeField(blank=True, null=True)),
                ('is_public_only', models.BooleanField(default=True)),
                ('can_access_dashboard', models.BooleanField(default=False)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='main.agency')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='main.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('upgraded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view dashboard'), ('manage_departments', 'Can manage departments'), ('manage_agencies', 'Can manage agencies'), ('manage_priority_areas', 'Can manage priority areas'), ('manage_deliverables', 'Can manage deliverables'), ('manage_all_initiatives', 'Can manage all initiatives'), ('view_all_reports', 'Can view all reports'), ('export_data', 'Can export data'), ('moderate_comments', 'Can moderate comments'), ('delete_any_comment', 'Can delete any comment'), ('pin_comments', 'Can pin important comments'), ('view_analytics', 'Can view engagement analytics'), ('manage_public_users', 'Can manage public users'), ('manage_users', 'Can manage users'), ('manage_roles', 'Can manage roles and permissions')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('initiative_created', 'Initiative Created'), ('update', 'Update'), ('initiative_updated', 'Initiative Updated'), ('delete', 'Delete'), ('initiative_deleted', 'Initiative Deleted'), ('progress_recorded', 'Progress Recorded'), ('view', 'View'), ('export', 'Export'), ('generate_report', 'Generate Report'), ('report_generated', 'Report Generated'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile'), ('user_upgraded', 'User Upgraded'), ('role_assigned', 'Role Assigned')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
