# Generated by Django 4.2.16 on 2026-04-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
