# Generated by Django 4.2.16 on 2026-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_department_user_phone_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('project_created', 'Project Created'), ('update', 'Update'), ('project_updated', 'Project Updated'), ('delete', 'Delete'), ('project_deleted', 'Project Deleted'), ('view', 'View'), ('export', 'Export'), ('generate_report', 'Generate Report'), ('report_generated', 'Report Generated'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile')], max_length=50),
        ),
    ]
