# Generated by Django 4.2.16 on 2026-04-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0005_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('manage_ministries', 'Can manage ministries'), ('manage_priority_areas', 'Can manage priority areas'), ('manage_deliverables', 'Can manage deliverables'), ('manage_all_projects', 'Can manage all projects'), ('view_all_reports', 'Can view all reports'), ('export_data', 'Can export data'), ('moderate_comments', 'Can moderate comments'), ('delete_any_comment', 'Can delete any comment'), ('pin_comments', 'Can pin important comments'), ('view_analytics', 'Can view engagement analytics'), ('manage_public_users', 'Can manage public users'), ('manage_users', 'Can manage users'), ('manage_roles', 'Can manage roles and permissions')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_public_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ministry'),
        ),
    ]
