# Generated by Django 4.2.16 on 2026-04-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_remove_user_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ministry',
            new_name='assigned_ministry',
        ),
        migrations.AddField(
            model_name='user',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upgraded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public_only',
            field=models.BooleanField(default=True),
        ),
    ]
