# Generated by Django 4.2.16 on 2026-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_ministry_user_assigned_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
