# Generated by Django 4.2.16 on 2026-04-09 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinitiative',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_initiatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinitiative',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_initiatives', to=settings.AUTH_USER_MODEL),
        ),
    ]
