# Generated by Django 4.2.16 on 2026-04-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0001_initial'),
        ('main', '0002_projectinitiative_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_accuracy', models.CharField(choices=[('available', 'Data Available - Verified'), ('not_available', 'Data Not Available'), ('inaccurate', 'Data Not Accurate'), ('not_verifiable', 'Data Not Verifiable')], max_length=20)),
                ('effort_percentage', models.IntegerField(help_text='Efforts towards achieving goals (%)')),
                ('expert_comment', models.TextField()),
                ('expert_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_assessment', to='main.projectinitiative')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeQuarterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('annual_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_achievement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_summaries', to='main.projectinitiative')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('initiative', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DeliverableQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan - Mar)'), (2, 'Q2 (Apr - Jun)'), (3, 'Q3 (Jul - Sep)'), (4, 'Q4 (Oct - Dec)')])),
                ('year', models.IntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft (Staff Working)'), ('submitted', 'Submitted for Review'), ('approved', 'Approved by Director'), ('rejected', 'Rejected'), ('assessed', 'Assessed by Expert')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('staff_comment', models.TextField(blank=True)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quarters', to=settings.AUTH_USER_MODEL)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_progress', to='main.deliverable')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_progress', to='main.projectinitiative')),
                ('progress_images', models.ManyToManyField(blank=True, related_name='quarter_progress', to='engagement.projectimage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quarters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'quarter'],
                'unique_together': {('initiative', 'deliverable', 'quarter', 'year')},
            },
        ),
    ]
