# Generated by Django 4.2.16 on 2026-04-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscommenter',
            options={'verbose_name': 'Anonymous Commenter', 'verbose_name_plural': 'Anonymous Commenters'},
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'session_id'), ('comment', 'anonymous_user')},
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='public_user',
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='engagement.anonymouscommenter'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'session_id'), ('comment', 'anonymous_user'), ('comment', 'user')},
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='public_user',
        ),
        migrations.DeleteModel(
            name='PublicUser',
        ),
    ]
